### ISSUE TITLE
Add a Demo

### ISSUE THREAD

**Issue by odahcam** [marvindanig/flippy.JS#3]
I'm trying to test your plugin without spending my time trying to make this work. A demo would be useful for testing and deciding before spending like an hour solving the test code errors on a local repo.

**Comment by marvindanig** [comment]
Oh, it's only 30% worked out at the moment -- will definitely add a demo and documentation to this. Thanks!

**Comment by odahcam** [comment]
@marvindanig oh, cool. This means that the plugin/library/app will be much better. Will you make something like [TurnJS](http://www.turnjs.com/#samples/docs/30) with a lot of animations and interactivity?

**Comment by marvindanig** [comment]
yes!, a lot more performant and interactive than turnjs! btw have you seen this (a demo): 

https://bubbl.in/book/bookiza-documentation-by-marvin-danig/1

**Comment by odahcam** [comment]
I found it very cool, but extremely heavy, the "demo" was laggy in Chrome with 24GB RAM. I'm working on a responsive TurnJS version that is able to take the page content width and adapt itself.

**Comment by marvindanig** [comment]
Awesome, looking forward for your tweak of responsive turnjs!

Yeah, this demo is using modified turnjs underneath with the same thing -- responsive widths etc. It works kinda okay on my 4GB MBP but may be an investigation on what pieces introduce the jank in this demo will help?

**Comment by odahcam** [comment]
Sure, but it will help you with something? If it doesn't I think it's not a good ideia. hehe
----
Here's an working version of my TurnJS fork: http://gilzer.com.br/catalogo.php?colecao=fit-together

I'm updating this right now, so in a few days this live version will be replaced with a better one.

Initialy I came here to search a new e-book creation tool, but as yours is not ready iet I'll continue do update my fork.

We could share some code. 😉
