### ISSUE TITLE
Cannot implement draggable element on page

### ISSUE THREAD

**Issue by martinhbramwell** [marvindanig/flippy.JS#9]
The page turning functionality interferes with other mouse/touch activity.

When attempting to drag a button on a page the page turning functionality always activates and the folded page hides the draggable ```div```. Releasing the mouse button releases the page and the draggable ```div``` can then be moved on its own. A final click deposits it in the desired place.

I create a button in a ```div``` with a drag handle, like this:
```
<div class="leaf flex bgnd">

  <!-- Draggable DIV -->
  <div id="mydiv">
    <div id="mydivheader"/>
    <button class="button">Go</button>
  </div> 
</div>
```

I implement dragging like this:
```
// Make the DIV element draggable:
dragElement(document.getElementById("mydiv"));

function dragElement(elmnt) {
  var pos1 = 0, pos2 = 0, pos3 = 0, pos4 = 0;
  if (document.getElementById(elmnt.id + "header")) {
    // if present, the header is where you move the DIV from:
    document.getElementById(elmnt.id + "header").onmousedown = dragMouseDown;
  } else {
    // otherwise, move the DIV from anywhere inside the DIV:
    elmnt.onmousedown = dragMouseDown;
  }

  function dragMouseDown(e) {
    e = e || window.event;
    e.preventDefault();
    // get the mouse cursor position at startup:
    pos3 = e.clientX;
    pos4 = e.clientY;
    document.onmouseup = closeDragElement;
    // call a function whenever the cursor moves:
    document.onmousemove = elementDrag;
  }

  function elementDrag(e) {
    e = e || window.event;
    e.preventDefault();
    // calculate the new cursor position:
    pos1 = pos3 - e.clientX;
    pos2 = pos4 - e.clientY;
    pos3 = e.clientX;
    pos4 = e.clientY;
    // set the element's new position:
    elmnt.style.top = (elmnt.offsetTop - pos2) + "px";
    elmnt.style.left = (elmnt.offsetLeft - pos1) + "px";
  }

  function closeDragElement() {
    // stop moving when mouse button is released:
    document.onmouseup = null;
    document.onmousemove = null;
  }
}
```

---
Question:
*How can my draggable div avoid interference from the page turning capability?*

**Comment by marvindanig** [comment]
To prevent an area on page from turning, use the `turnoff` className on your element. Then inside that element, you can do whatever you want with javascript.

**Tip:** Avoid using `turnoff` at the leaf level for accessibility. On some mobile phones and a few older iPads, there will be no way for the user to turn the page over once they are on a leaf on which flipping has been turned off.  🤙🏻

**Comment by martinhbramwell** [comment]
I think there is more going on in this issue.

I have found no way to apply "turnoff" to the draggable in code.

If I put "turnoff" in my draggable ```div``` like this ...
```
<!-- Draggable DIV -->
<div id="mydiv" class="turnoff">
  <div id="mydivheader">
```

... then, while page turning functions as normal, control over the draggable is defective.  Dragging begins, without turning the page, but then the draggable item remains permanently "stuck" to the cursor.

I've been trying various tricks but I can see no way to make the cursor drop the draggable on mouse up.
Am I missing something?

**Comment by marvindanig** [comment]
hm. Can you share the code that you've written for this? 

Feel free to invite me over a private manuscript repo if that works better for your book. 🙏🏻
